# Generated by Django 4.0.3 on 2022-04-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overseasApp', '0002_student_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='Planning_Apply_In',
            new_name='Planning_Apply_In_Year',
        ),
    ]
