# Generated by Django 4.0.3 on 2022-04-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseasApp', '0003_rename_planning_apply_in_student_info_planning_apply_in_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='Planning_Apply_In_Year',
            field=models.CharField(max_length=255),
        ),
    ]
