# Generated by Django 4.0.3 on 2022-04-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseasApp', '0005_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Due_Payment',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
