# Generated by Django 4.0.3 on 2022-04-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseasApp', '0006_alter_invoice_due_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Order_No',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
